### ISSUE TITLE
Форма регистрация/авторизация

### ISSUE THREAD

**Issue by AlexeyPM** [encryption-machine/Front#10]

**Comment by teplostanski** [comment]
2 дня

**Comment by AlexeyPM** [comment]
https://www.figma.com/file/GeQNLpMLM84mA37u3fbfKs/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%22%D0%A8%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B0%22?type=design&node-id=218%3A2&t=yRVysuxooLSxaABH-1
