### ISSUE TITLE
Разработать форму сброса пароля

### ISSUE THREAD

**Issue by younamono** [encryption-machine/Front#42]
Форма отрисована, взять ее можно тут: https://www.figma.com/file/sXoX6dcw6Z1RoAZCmAe6BA/%D0%A8%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D0%B0-(%D0%94%D0%B8%D0%B7%D0%B0%D0%B9%D0%BD)?type=design&node-id=7%3A5365&mode=design&t=Z7BPr9cLrOz2RLOs-1

**Comment by teplostanski** [comment]
18.06
